-- Initial schema for the restaurant ordering system.
-- PostgreSQL 16 / Flyway migration.

CREATE TABLE stores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    version INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NULL,
    cognito_user_id VARCHAR(255) NOT NULL UNIQUE,
    role VARCHAR(30) NOT NULL,
    user_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    version INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE restaurant_tables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    table_number VARCHAR(20) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'AVAILABLE',
    qr_token VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    version INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uq_restaurant_tables_store_table_number UNIQUE (store_id, table_number)
);

CREATE TABLE visit_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    table_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    visit_token VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ended_at TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE menu_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    version INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uq_menu_categories_store_name UNIQUE (store_id, name)
);

CREATE TABLE menus (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_category_id BIGINT NOT NULL,
    store_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    price INTEGER NOT NULL,
    description TEXT NULL,
    image_url VARCHAR(255) NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'AVAILABLE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    version INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uq_menus_store_category_name UNIQUE (store_id, menu_category_id, name)
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_session_id BIGINT NOT NULL,
    store_id BIGINT NOT NULL,
    table_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ORDERED',
    total_amount INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    version INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    menu_id BIGINT NOT NULL,
    cooking_status VARCHAR(30) NOT NULL DEFAULT 'WAITING',
    quantity INTEGER NOT NULL,
    unit_price INTEGER NOT NULL,
    subtotal_amount INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    version INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    visit_session_id BIGINT NOT NULL UNIQUE,
    amount INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    paid_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    version INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE daily_sales_summaries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    sales_date DATE NOT NULL,
    total_sales_amount INTEGER NOT NULL DEFAULT 0,
    total_order_count INTEGER NOT NULL DEFAULT 0,
    total_customer_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_daily_sales_summaries_store_sales_date UNIQUE (store_id, sales_date)
);

CREATE TABLE batch_job_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NULL,
    job_name VARCHAR(100) NOT NULL,
    status VARCHAR(30) NOT NULL,
    target_date DATE NULL,
    start_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_time TIMESTAMP NULL,
    error_message TEXT NULL
);

-- Foreign keys.
ALTER TABLE stores
    ADD CONSTRAINT fk_stores_created_by FOREIGN KEY (created_by) REFERENCES users(id),
    ADD CONSTRAINT fk_stores_updated_by FOREIGN KEY (updated_by) REFERENCES users(id);

ALTER TABLE users
    ADD CONSTRAINT fk_users_store_id FOREIGN KEY (store_id) REFERENCES stores(id),
    ADD CONSTRAINT fk_users_created_by FOREIGN KEY (created_by) REFERENCES users(id),
    ADD CONSTRAINT fk_users_updated_by FOREIGN KEY (updated_by) REFERENCES users(id);

ALTER TABLE restaurant_tables
    ADD CONSTRAINT fk_restaurant_tables_store_id FOREIGN KEY (store_id) REFERENCES stores(id),
    ADD CONSTRAINT fk_restaurant_tables_created_by FOREIGN KEY (created_by) REFERENCES users(id),
    ADD CONSTRAINT fk_restaurant_tables_updated_by FOREIGN KEY (updated_by) REFERENCES users(id);

ALTER TABLE visit_sessions
    ADD CONSTRAINT fk_visit_sessions_store_id FOREIGN KEY (store_id) REFERENCES stores(id),
    ADD CONSTRAINT fk_visit_sessions_table_id FOREIGN KEY (table_id) REFERENCES restaurant_tables(id);

ALTER TABLE menu_categories
    ADD CONSTRAINT fk_menu_categories_store_id FOREIGN KEY (store_id) REFERENCES stores(id),
    ADD CONSTRAINT fk_menu_categories_created_by FOREIGN KEY (created_by) REFERENCES users(id),
    ADD CONSTRAINT fk_menu_categories_updated_by FOREIGN KEY (updated_by) REFERENCES users(id);

ALTER TABLE menus
    ADD CONSTRAINT fk_menus_menu_category_id FOREIGN KEY (menu_category_id) REFERENCES menu_categories(id),
    ADD CONSTRAINT fk_menus_store_id FOREIGN KEY (store_id) REFERENCES stores(id),
    ADD CONSTRAINT fk_menus_created_by FOREIGN KEY (created_by) REFERENCES users(id),
    ADD CONSTRAINT fk_menus_updated_by FOREIGN KEY (updated_by) REFERENCES users(id);

ALTER TABLE orders
    ADD CONSTRAINT fk_orders_visit_session_id FOREIGN KEY (visit_session_id) REFERENCES visit_sessions(id),
    ADD CONSTRAINT fk_orders_store_id FOREIGN KEY (store_id) REFERENCES stores(id),
    ADD CONSTRAINT fk_orders_table_id FOREIGN KEY (table_id) REFERENCES restaurant_tables(id),
    ADD CONSTRAINT fk_orders_created_by FOREIGN KEY (created_by) REFERENCES users(id),
    ADD CONSTRAINT fk_orders_updated_by FOREIGN KEY (updated_by) REFERENCES users(id);

ALTER TABLE order_items
    ADD CONSTRAINT fk_order_items_order_id FOREIGN KEY (order_id) REFERENCES orders(id),
    ADD CONSTRAINT fk_order_items_menu_id FOREIGN KEY (menu_id) REFERENCES menus(id),
    ADD CONSTRAINT fk_order_items_updated_by FOREIGN KEY (updated_by) REFERENCES users(id);

ALTER TABLE payments
    ADD CONSTRAINT fk_payments_store_id FOREIGN KEY (store_id) REFERENCES stores(id),
    ADD CONSTRAINT fk_payments_visit_session_id FOREIGN KEY (visit_session_id) REFERENCES visit_sessions(id),
    ADD CONSTRAINT fk_payments_created_by FOREIGN KEY (created_by) REFERENCES users(id),
    ADD CONSTRAINT fk_payments_updated_by FOREIGN KEY (updated_by) REFERENCES users(id);

ALTER TABLE daily_sales_summaries
    ADD CONSTRAINT fk_daily_sales_summaries_store_id FOREIGN KEY (store_id) REFERENCES stores(id);

ALTER TABLE batch_job_histories
    ADD CONSTRAINT fk_batch_job_histories_store_id FOREIGN KEY (store_id) REFERENCES stores(id);

-- Search indexes.
CREATE INDEX idx_users_store_id
    ON users (store_id);

CREATE INDEX idx_visit_sessions_table_id_status
    ON visit_sessions (table_id, status);

CREATE INDEX idx_orders_visit_session_id
    ON orders (visit_session_id);

CREATE INDEX idx_orders_store_id_created_at
    ON orders (store_id, created_at);

CREATE INDEX idx_order_items_order_id
    ON order_items (order_id);

CREATE INDEX idx_payments_store_id_paid_at
    ON payments (store_id, paid_at);
